# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7.7'
        architecture: 'x64'
    - name: Install Matplotlib and Basemap
      run: pip install --upgrade --user matplotlib numpy pyproj pyshp pywaffle beautifulsoup4 OWSLib Pillow && sudo apt install libgeos-dev && sudo apt-get update && sudo apt install libgeos-dev && pip install --user https://github.com/matplotlib/basemap/archive/master.zip
    - name: Install Other Packages and Extensions
      run:  pip install jupyterlab jupyter_contrib_nbextensions papermill numpy pandas ipynb ipinfo && jupyter contrib nbextension install --user
    - name: Enable Jupyter Extensions
      run: jupyter nbextension enable python-markdown/main
    - name: Generate medalla html
      run: cd analysis && cat testnet-analysis.ipynb | papermill -p LOAD_SESSION True -p NETWORK "medalla" -p FORK_DIGEST "e7a75d5a" | jupyter nbconvert --stdin --TemplateExporter.exclude_input=True --to html --output ../medalla-analysis.html && cd ..
    - name: Move files
      run: mkdir -p public && mv *.html public/ && cp README.md public/index.md
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: ./public
        enable_jekyll: true
        keep_files: true

