# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Install JupyterLab, Papermill and Extensions
      run: pip install jupyterlab && pip install papermill && pip install jupyter_contrib_nbextensions && jupyter contrib nbextension install --user
    - name: Enable Jupyter Extensions
      run: jupyter nbextension enable python-markdown/main
    - name: Generate topaz html 
      run: cat analysis/testnet-analysis.ipynb | papermill -p NETWORK "topaz" -p FORK_DIGEST "f071c66c" | jupyter nbconvert --stdin --TemplateExporter.exclude_input=True --to html --output topaz-analysis.html
    - name: Generate witti html
      run: cat analysis/testnet-analysis.ipynb | papermill -p NETWORK "witti" -p FORK_DIGEST "f6775d07" | jupyter nbconvert --stdin --TemplateExporter.exclude_input=True --to html --output witti-analysis.html 
    - name: Move files
      run: mkdir -p public && mv *.html public/ && cp README.md public/index.md
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: ./public

